baseURL = 'https://minghanxchiang.github.io'
languageCode = 'en-us'
title = 'Data Travelogue by Daniel Chiang'
theme = 'hugo-theme-cleanwhite'
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
pagination.pagerSize = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/Rochester Chicago 2022.jpg"
  SEOTitle = "蔣明翰的部落格 | Daniel Chiang's Blog"
  description = ""
  keyword = ""
  slogan = "Forget Bacchus in the Arms of Morpheus."
  upstreamAttribution = true

  math = true

  custom_css = ["css/custom.css"]

  image_404 = ""
  title_404 = "It's still an unexplored place here."
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Newbie Data Science Enthusiast, Fulltime Foodie, Parttime Traveler" 
  sidebar_avatar = "img/IMG_8986.JPG"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1

  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = false 
  email          = "minghanxchiang@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/daniel-minghan-chiang-b27637117"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  #github         = "https://github.com/yourgithub"
  #wechat         = "your wechat qr code image"
  medium        = "https://medium.com/@daniel84101"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #git           = "full profile url for git user"

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]